# Generated by Django 3.2.11 on 2022-02-21 05:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0011_auto_20220221_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 5, 53, 44, 729475, tzinfo=utc), editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 5, 53, 44, 729475, tzinfo=utc), verbose_name='Edited'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 5, 53, 44, 728475, tzinfo=utc), editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 5, 53, 44, 728475, tzinfo=utc), verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
