# Generated by Django 3.2.11 on 2022-02-21 22:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_auto_20220221_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 22, 24, 16, 246465, tzinfo=utc), editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='edited',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 22, 24, 16, 246465, tzinfo=utc), verbose_name='Edited'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 22, 24, 16, 246465, tzinfo=utc), editable=False, verbose_name='Created'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 21, 22, 24, 16, 245435, tzinfo=utc), verbose_name='Created'),
        ),
    ]
